name: Main
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Build and Test
        run: |
          echo "Your build/test commands"

      - run: |
          gh workflow dispatch -y release.yml -i environment=develop
