name: build

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: 'zulu'
      - run: "echo build"
