name: release

on:
  workflow_run:
    workflows: [build]
    types: [completed]
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps: 
      - run: "echo Deployment"
