name: "release"

on:
  workflow_run:
    workflows: [Build]
    types: [completed]
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
  
    steps: 
      - run: "echo Deployment"
